### ISSUE TITLE
third_robot_gazeboをここに移行して欲しい

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT-Unit03/cirkit_unit03_simulator#1]
すみません，[https://github.com/CIR-KIT/third_robot_pkg/tree/master/third_robot_gazebo](third_robot_gazebo) をこのリポジトリに移行してもらえますか？

https://github.com/CIR-KIT-Unit03/cirkit_unit03/issues/11 を解決するために必要です．

それか，コミットログを引き継いだまま，特定のパッケージだけ移行する方法を教えてもらえますか？^^；

**Comment by AriYu** [comment]
Pull #2 で一応解決しました。
